name: Fetch & Parse Daily Sun

on:
  schedule:
    - cron: "15 * * * *"  # Adjust as needed
  workflow_dispatch:

jobs:
  fetch_and_parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch Print Version & Subcategories HTMLs
        run: python fetch_htmls.py

      - name: Parse HTMLs to XML
        run: python parse_to_xml.py

      - name: Commit all HTML and XML files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.html *.xml
          git commit -m "Daily update of HTMLs & XMLs" || echo "No changes to commit"
          git push